using AlgorithmExplorer.Application.ExecutionCoordinators.Base;

namespace AlgorithmExplorer.Application.ExecutionCoordinators.MatrixMultiplication;

public class MatrixMultiplicationCoordinatorOptions : CoordinatorOptionsBase
{
}